(defun sweep-buffer ()
  (interactive)
  (setq verbose t)
  (setq result-buffer-name (generate-new-buffer-name "*sweep-buffer*"))
  (setq index 0)
  (setq l (length (buffer-list)))
  (generate-new-buffer result-buffer-name)
  (switch-to-buffer result-buffer-name)
  (while (< index l)
    (setq b (nth index (buffer-list)))
    (setq name (buffer-name b))
    (setq file-name (buffer-file-name b))
    (setq mode (format "%s" (buffer-local-value 'major-mode b)))
    (setq flag (or (string= mode "dired-mode") file-name))
    (if verbose
      (insert (concat "============\n" (if flag "[clear]" "[pass]") "\n" name "\n" file-name "\n" mode "\n"))
      (if flag (insert (concat "[clear]\t" name "\n"))))
    (if flag (kill-buffer b))
    (setq index (+ index 1))))
