(defun each-buffer (iterator &optional bufs)
  (setq bufs (if bufs bufs (buffer-list)))
  (funcall iterator (car bufs))
  (if (cdr bufs) (each-buffer iterator (cdr bufs))))

(defun sweep-buffer ()
  (interactive)
  (setq verbose nil)
  (setq result-buffer-name (generate-new-buffer-name "*sweep-buffer*"))
  (generate-new-buffer result-buffer-name)
  (switch-to-buffer result-buffer-name)
  (each-buffer '(lambda (buf)
                  (setq name (buffer-name buf))
                  (setq file-name (buffer-file-name buf))
                  (setq mode (format "%s" (buffer-local-value 'major-mode buf)))
                  (setq flag (or (string= mode "dired-mode") file-name))
                  (if flag
                      (let ()
                        (insert (concat "[clear]\t" name "\n"))
                        (if flag (kill-buffer buf)))))))
